/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this
 * license Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.teleamiguis;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
import static services.Reportes.createPrint;
import static services.Reportes.createReportView;
import static services.Reportes.getConnection;
import modules.AdministradorUsuarios;
import modules.AutoCompletion;

/**
 *
 * @author gyron
 */
public class Administrador extends javax.swing.JFrame {

    private AdministradorUsuarios admUser;
    private String idActual;
    private String tipoidActual;
    int xMouse;
    int yMouse;
    String idUsuario;
    String tipoidUsuario;

    /**
     * Creates new form Gerente
     */
    public Administrador(String id, String tipoid, String nombreUser) {
        initComponents();

        idUsuario = id;
        tipoidUsuario = tipoid;

        tituloSuperior.setText("Usuario " + nombreUser);

        try {
            // Hacemos invisibles todos los jlabel de abajo del tab de gestionUsuario
            admUser = new AdministradorUsuarios(); // se crea una instancia de la clase
                                                   // AdministradorUsuarios
        } catch (IOException | SQLException e) {
            System.out.println("Hubo un problema al crear la clase administradorUsuario");
        }

        estadoventanasEstadoUsuario(false);
        estadoventanasConsultaUsuario(true);
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelGeneral = new javax.swing.JPanel();
        panelIzq = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        horaSesion = new javax.swing.JLabel();
        usuarios = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        salida = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        panelDer = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();
        tabsUsuarios = new javax.swing.JTabbedPane();
        tabGestiosUsuarios = new javax.swing.JPanel();
        label_id = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        label_dir = new javax.swing.JLabel();
        label_tel = new javax.swing.JLabel();
        label_mail = new javax.swing.JLabel();
        label_estado = new javax.swing.JLabel();
        label_titulo = new javax.swing.JLabel();
        label_cargo = new javax.swing.JLabel();
        label_resul_estado = new javax.swing.JLabel();
        jTF_resul_nombre = new javax.swing.JTextField();
        jTF_resul_dir = new javax.swing.JTextField();
        jTF_resul_tel = new javax.swing.JTextField();
        jTF_resul_mail = new javax.swing.JTextField();
        jTF_resul_id = new javax.swing.JTextField();
        cambiarEstado = new javax.swing.JButton();
        campoConsultaUsuario = new javax.swing.JComboBox<>();
        actualiarInfo = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        label_notificacion = new javax.swing.JLabel();
        label_resulEstado2 = new javax.swing.JLabel();
        jTF_resul_tipoid = new javax.swing.JComboBox<>();
        label_imEstado = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        jTF_resul_cargo = new javax.swing.JComboBox<>();
        tabsReportes = new javax.swing.JTabbedPane();
        reporteGanancias = new javax.swing.JPanel();
        reporteFacturas = new javax.swing.JPanel();
        reporteOperadores = new javax.swing.JPanel();
        reporteNose = new javax.swing.JPanel();
        barraTitulo = new javax.swing.JPanel();
        tituloSuperior = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelGeneral.setBackground(new java.awt.Color(98, 197, 255));
        panelGeneral.setPreferredSize(new java.awt.Dimension(850, 450));
        panelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIzq.setBackground(new java.awt.Color(22, 49, 92));
        panelIzq.setPreferredSize(new java.awt.Dimension(300, 450));
        panelIzq.setLayout(new java.awt.GridBagLayout());

        nombre.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("ADMINISTRADOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelIzq.add(nombre, gridBagConstraints);

        horaSesion.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        horaSesion.setForeground(new java.awt.Color(255, 255, 255));
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        horaSesion.setText(dtf.format(now));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 5);
        panelIzq.add(horaSesion, gridBagConstraints);

        usuarios.setBackground(new java.awt.Color(255, 255, 255));
        usuarios.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        usuarios.setForeground(new java.awt.Color(0, 0, 0));
        usuarios.setText("Usuarios");
        usuarios.setFocusPainted(false);
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(34, 10, 6, 10);
        panelIzq.add(usuarios, gridBagConstraints);

        reportes.setBackground(new java.awt.Color(255, 255, 255));
        reportes.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        reportes.setForeground(new java.awt.Color(0, 0, 0));
        reportes.setText("Reportes");
        reportes.setFocusable(false);
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelIzq.add(reportes, gridBagConstraints);

        salida.setBackground(new java.awt.Color(102, 102, 102));
        salida.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        salida.setForeground(new java.awt.Color(255, 255, 255));
        salida.setText("Salida");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(82, 10, 10, 10);
        panelIzq.add(salida, gridBagConstraints);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/Logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        panelIzq.add(Logo, gridBagConstraints);

        panelGeneral.add(panelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 450));

        panelDer.setBackground(new java.awt.Color(255, 255, 255,150));
        panelDer.setPreferredSize(new java.awt.Dimension(500, 450));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/fondo2.jpg"))); // NOI18N
        Fondo.setToolTipText("");
        Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabsUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabsUsuarios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsUsuariosStateChanged(evt);
            }
        });

        tabGestiosUsuarios.setBackground(new java.awt.Color(255, 255, 255, 150));
        tabGestiosUsuarios.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tabGestiosUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_id.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id.setText("Identificación");
        tabGestiosUsuarios.add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 188, 160, -1));
        label_id.setVisible(false);

        label_nombre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nombre.setText("Nombre");
        tabGestiosUsuarios.add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 188, 170, -1));
        label_nombre.setVisible(false);

        label_dir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_dir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dir.setText("Dirección");
        tabGestiosUsuarios.add(label_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 273, 160, -1));
        label_dir.setVisible(false);

        label_tel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_tel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tel.setText("Teléfono");
        tabGestiosUsuarios.add(label_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 273, 170, -1));
        label_tel.setVisible(false);

        label_mail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_mail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_mail.setText("Correo ");
        tabGestiosUsuarios.add(label_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 273, 170, -1));
        label_mail.setVisible(false);

        label_estado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_estado.setText("Estado");
        tabGestiosUsuarios.add(label_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 349, 170, -1));
        label_estado.setVisible(false);

        label_titulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_titulo.setText("Seleccione el documento de identidad:");
        tabGestiosUsuarios.add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 400, -1));

        label_cargo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_cargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cargo.setText("Cargo");
        tabGestiosUsuarios.add(label_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 188, 170, -1));
        label_cargo.setVisible(false);

        label_resul_estado.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_resul_estado.setForeground(new java.awt.Color(0, 153, 51));
        label_resul_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabGestiosUsuarios.add(label_resul_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 374, 173, 36));
        label_resul_estado.setVisible(false);

        jTF_resul_nombre.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_nombre.setEditable(true);
        jTF_resul_nombre.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_nombre.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_resul_nombre.setOpaque(true);
        tabGestiosUsuarios.add(jTF_resul_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 213, 173, 33));
        jTF_resul_nombre.setVisible(false);

        jTF_resul_dir.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_dir.setEditable(true);
        jTF_resul_dir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_dir.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_dir.setOpaque(true);
        tabGestiosUsuarios.add(jTF_resul_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 298, 170, 33));
        jTF_resul_dir.setVisible(false);

        jTF_resul_tel.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_tel.setEditable(true);
        jTF_resul_tel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_tel.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_resul_tel.setOpaque(true);
        tabGestiosUsuarios.add(jTF_resul_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 298, 173, 33));
        jTF_resul_tel.setVisible(false);

        jTF_resul_mail.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_mail.setEditable(true);
        jTF_resul_mail.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_mail.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_mail.setOpaque(true);
        tabGestiosUsuarios.add(jTF_resul_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 298, 173, 33));
        jTF_resul_mail.setVisible(false);

        jTF_resul_id.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_id.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_resul_idActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(jTF_resul_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 213, 100, 33));

        cambiarEstado.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cambiarEstado.setText("Activar/Desactivar");
        cambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarEstadoActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(cambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 180, -1));

        try {
            AdministradorUsuarios admUser = new AdministradorUsuarios();
            ArrayList<String[]> usuarios= admUser.mostrarListaUsuarios();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (String[] usuario: usuarios){
                model.addElement(usuario[0] +" - " + usuario[2] +" - " + usuario[1] );
            }
            campoConsultaUsuario.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
            campoConsultaUsuario.setModel(model);
        } catch (IOException | SQLException e) {
            System.out.println("No fue posible crear la clase administradorUsuarios");
        }
        campoConsultaUsuario.setSelectedIndex(-1);
        campoConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConsultaUsuarioActionPerformed(evt);
            }
        });
        AutoCompletion.enable(campoConsultaUsuario );
        tabGestiosUsuarios.add(campoConsultaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 300, 50));

        actualiarInfo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        actualiarInfo.setText("Actualizar información");
        actualiarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiarInfoActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(actualiarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 170, -1));

        Registrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 180, -1));

        label_notificacion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_notificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tabGestiosUsuarios.add(label_notificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 380, 40));

        label_resulEstado2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_resulEstado2.setForeground(new java.awt.Color(0, 153, 51));
        label_resulEstado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabGestiosUsuarios.add(label_resulEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 330, 50));
        label_resul_estado.setVisible(false);

        jTF_resul_tipoid.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_tipoid.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_tipoid.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_tipoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "T.I", "NIT"}));
        jTF_resul_tipoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_resul_tipoidActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(jTF_resul_tipoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 213, 60, 33));
        jTF_resul_tipoid.setSelectedIndex(-1);

        this.setVisible(false);
        label_imEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/estado_usuario.png"))); // NOI18N
        label_imEstado.setOpaque(true);
        tabGestiosUsuarios.add(label_imEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        jTF_resul_cargo.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_cargo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_cargo.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Operador", "Gerente" }));
        jTF_resul_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_resul_cargoActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(jTF_resul_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 213, 173, 33));
        jTF_resul_cargo.setSelectedIndex(-1);

        tabsUsuarios.addTab("Gestion", tabGestiosUsuarios);

        tabsReportes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsReportesStateChanged(evt);
            }
        });

        reporteGanancias.setBackground(new java.awt.Color(255, 255, 255, 150));
        reporteGanancias.setLayout(new java.awt.BorderLayout());
        tabsReportes.addTab("Ganancias", reporteGanancias);

        reporteFacturas.setBackground(new java.awt.Color(255, 255, 255, 150));
        reporteFacturas.setLayout(new java.awt.BorderLayout());
        tabsReportes.addTab("Facturas", reporteFacturas);

        reporteOperadores.setBackground(new java.awt.Color(255, 255, 255, 150));
        reporteOperadores.setLayout(new java.awt.BorderLayout());
        tabsReportes.addTab("Operadores", reporteOperadores);

        reporteNose.setBackground(new java.awt.Color(255, 255, 255, 150));
        reporteNose.setLayout(new java.awt.BorderLayout());
        tabsReportes.addTab("Nose", reporteNose);

        javax.swing.GroupLayout panelDerLayout = new javax.swing.GroupLayout(panelDer);
        panelDer.setLayout(panelDerLayout);
        panelDerLayout.setHorizontalGroup(
            panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabsUsuarios))
            .addGroup(panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelDerLayout.setVerticalGroup(
            panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addGroup(panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDerLayout.createSequentialGroup()
                    .addComponent(tabsUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDerLayout.createSequentialGroup()
                    .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        //Colocar font a las ventanas
        tabsUsuarios.setFont( new Font("Sansserif", Font.BOLD, 12));
        //Poner invisible al inicio tab Usuarios
        tabsUsuarios.setVisible(false);
        //Poner invisible all inicio
        tabsReportes.setVisible(false);

        panelGeneral.add(panelDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 700, 450));
        panelDer.getAccessibleContext().setAccessibleDescription("");

        barraTitulo.setBackground(new java.awt.Color(43, 41, 40));
        barraTitulo.setForeground(new java.awt.Color(255, 255, 255));
        barraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraTituloMouseDragged(evt);
            }
        });
        barraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraTituloMousePressed(evt);
            }
        });

        tituloSuperior.setBackground(new java.awt.Color(0, 0, 0));
        tituloSuperior.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tituloSuperior.setForeground(new java.awt.Color(255, 255, 255));
        tituloSuperior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloSuperior.setText("Administrador");

        javax.swing.GroupLayout barraTituloLayout = new javax.swing.GroupLayout(barraTitulo);
        barraTitulo.setLayout(barraTituloLayout);
        barraTituloLayout.setHorizontalGroup(
            barraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        barraTituloLayout.setVerticalGroup(
            barraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloSuperior)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGeneral.add(barraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_resul_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_resul_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_resul_idActionPerformed

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usuariosActionPerformed
        tabsReportes.setVisible(false);
        tabsUsuarios.setVisible(true);
        panelGeneral.repaint();
        panelGeneral.revalidate();
        panelDer.repaint();
        panelDer.revalidate();
        reportes.setEnabled(true);
        usuarios.setEnabled(false);

    }// GEN-LAST:event_usuariosActionPerformed

    private void barraTituloMouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_barraTituloMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }// GEN-LAST:event_barraTituloMouseDragged

    private void barraTituloMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_barraTituloMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }// GEN-LAST:event_barraTituloMousePressed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salidaActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            admUser.cerrarConexion(idUsuario, tipoidUsuario);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        Login login = new Login();
        login.setVisible(true);
    }// GEN-LAST:event_salidaActionPerformed

    private void estadoClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoClientesActionPerformed
        tabsReportes.setVisible(false);
        tabsUsuarios.setVisible(false);
        panelGeneral.repaint();
        panelGeneral.revalidate();
        panelDer.repaint();
        panelDer.revalidate();
        reportes.setEnabled(true);
        usuarios.setEnabled(true);

    }// GEN-LAST:event_estadoClientesActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_reportesActionPerformed
        tabsReportes.setVisible(true);
        tabsUsuarios.setVisible(false);
        panelGeneral.repaint();
        panelGeneral.revalidate();
        panelDer.repaint();
        panelDer.revalidate();
        reportes.setEnabled(false);
        usuarios.setEnabled(true);

    }// GEN-LAST:event_reportesActionPerformed

    private void tabsReportesStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_tabsReportesStateChanged
        if (tabsReportes.getSelectedIndex() == 0) {
            try {
                Connection conn = getConnection();
                Map<String, Object> parameters = new HashMap<>();
                parameters.put("title", "Soy un titulo mamon");
                String jrxml = "/reports/reportes.jrxml";
                JasperPrint print = createPrint(parameters, jrxml, conn);
                JRViewer view = createReportView(print);
                reporteGanancias.add(view);
                conn.close();

            } catch (JRException | IOException | SQLException ex) {
                Logger.getLogger(Gerente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // else{
        //
        // }

    }// GEN-LAST:event_tabsReportesStateChanged

    private void tabsUsuariosStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_tabsUsuariosStateChanged
        // TODO add your handling code here:
    }// GEN-LAST:event_tabsUsuariosStateChanged

    private void actualiarInfoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_actualiarInfoActionPerformed


        try {
            int returnCode;
            String datos[] = {String.valueOf(jTF_resul_cargo.getSelectedItem()),
                    jTF_resul_nombre.getText(), jTF_resul_dir.getText(), jTF_resul_tel.getText(),
                    jTF_resul_mail.getText(), jTF_resul_id.getText(),
                    String.valueOf(jTF_resul_tipoid.getSelectedItem())};

            if (!idActual.equals(datos[5]) && !tipoidActual.equals(datos[6])) {
                JOptionPane.showMessageDialog(null,
                        "No es posible editar el documento de identificación", "Advertencia",
                        JOptionPane.ERROR_MESSAGE);
                jTF_resul_id.setText(idActual);
            } else {

                returnCode = admUser.modificarUsuario(datos);



                if (returnCode == 1) {
                    ArrayList<String[]> usuarios = admUser.mostrarListaUsuarios();
                    DefaultComboBoxModel model = new DefaultComboBoxModel();
                    for (String[] usuario : usuarios) {
                        model.addElement(usuario[0] + " - " + usuario[2] + " - " + usuario[1]);
                    }
                    campoConsultaUsuario.setModel(model);
                    campoConsultaUsuario.setSelectedItem(jTF_resul_nombre.getText() + " - "
                            + String.valueOf(jTF_resul_tipoid.getSelectedItem()) + " - "
                            + jTF_resul_id.getText());

                    validate();
                    repaint();
                    JOptionPane.showMessageDialog(null, "Se actulizo la informacion");


                } else {
                    JOptionPane.showMessageDialog(null, "No fue posible actualizar la informacion",
                            "Advertencia", JOptionPane.ERROR_MESSAGE);
                }
            }


        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }// GEN-LAST:event_actualiarInfoActionPerformed

    private void cambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cambiarEstadoActionPerformed

        estadoventanasConsultaUsuario(false); // Se ocultan los posibles jlabels sobrepuestos

        int op;
        String info[] = String.valueOf(campoConsultaUsuario.getSelectedItem()).split(" - ");
        String id = info[2];
        String tipoid = info[1];
        String user;
        String[] datos;

        try {
            datos = admUser.mostrarUsuario(id, tipoid);
            if ("ACTIVO".equals(datos[7])) { // En el caso de que esté activo
                user = "" + datos[2] + " " + datos[3]
                        + " esta a punto de ser desactivado, ¿desea continuar?";
                op = JOptionPane.showConfirmDialog(null, user, "Desactivar usuario",
                        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
                        new javax.swing.ImageIcon(
                                getClass().getResource("/usedPictures/inactivar.png")));

                if (op == 0) {
                    admUser.cambiaEstadoUsuario(id, tipoid, "false");
                    label_notificacion.setText("El usuario con identificación " + id + " ha sido:");
                    label_resulEstado2.setText("DESACTIVADO");
                    label_resulEstado2.setForeground(new java.awt.Color(255, 51, 51)); // color rojo
                    estadoventanasEstadoUsuario(true);
                } else {
                    JOptionPane.showMessageDialog(null, "No se han aplicado cambios",
                            "Notificacion", JOptionPane.INFORMATION_MESSAGE,
                            new javax.swing.ImageIcon(
                                    getClass().getResource("/usedPictures/estado_usuario.png")));
                    estadoventanasEstadoUsuario(false);
                }
            } else { // En el caso de que esté inactivo
                user = "" + datos[2] + " " + datos[3]
                        + " esta a punto de ser reactivado, ¿desea continuar?";
                op = JOptionPane.showConfirmDialog(null, user, "Activar usuario",
                        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
                        new javax.swing.ImageIcon(
                                getClass().getResource("/usedPictures/activar.png")));
                if (op == 0) {
                    admUser.cambiaEstadoUsuario(id, tipoid, "true");
                    label_notificacion.setText("El usuario con identificación " + id + " ha sido:");
                    label_resulEstado2.setText("ACTIVADO");
                    label_resulEstado2.setForeground(new java.awt.Color(0, 153, 51)); // color verde
                    estadoventanasEstadoUsuario(true);
                } else {
                    JOptionPane.showMessageDialog(null, "No se han aplicado cambios",
                            "Notificacion", JOptionPane.INFORMATION_MESSAGE,
                            new javax.swing.ImageIcon(
                                    getClass().getResource("/usedPictures/estado_usuario.png")));
                    estadoventanasEstadoUsuario(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }


    }// GEN-LAST:event_cambiarEstadoActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegistrarActionPerformed

        String datos[] = {jTF_resul_id.getText(),
                String.valueOf(jTF_resul_tipoid.getSelectedItem()),
                String.valueOf(jTF_resul_cargo.getSelectedItem()), jTF_resul_nombre.getText(),
                jTF_resul_dir.getText(), jTF_resul_tel.getText(), jTF_resul_mail.getText()};

        try {

            int confirmacion = admUser.registrarUsuario(datos);
            ArrayList<String[]> usuarios = admUser.mostrarListaUsuarios();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (String[] usuario : usuarios) {
                model.addElement(usuario[0] + " - " + usuario[2] + " - " + usuario[1]);
            }
            campoConsultaUsuario.setModel(model);

            validate();
            repaint();
            campoConsultaUsuario.setSelectedIndex(-1);

            if (confirmacion == -1) {
                JOptionPane.showMessageDialog(null,
                        "No fue posible registrar al usuario ingresado, dato inválido",
                        "Notificación", JOptionPane.ERROR_MESSAGE);
            }
            if (confirmacion == 2) {
                JOptionPane.showMessageDialog(null,
                        "No fue posible registrar al usuario ingresado, datos vacios",
                        "Notificación", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Se registró el usuario ingresado",
                        "Notificación", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException | SQLException e) {
            JOptionPane.showMessageDialog(null, "No fue posible ingresar al usuario vacio",
                    "Notificación", JOptionPane.ERROR_MESSAGE);
        }


    }// GEN-LAST:event_RegistrarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LimpiarActionPerformed

        limpiar();
    }// GEN-LAST:event_LimpiarActionPerformed


    private void limpiar() {
        campoConsultaUsuario.setSelectedIndex(-1);
        idActual = "";
        jTF_resul_id.setText("");
        jTF_resul_tipoid.setSelectedIndex(-1);
        jTF_resul_nombre.setText("");
        jTF_resul_cargo.setSelectedIndex(-1);
        jTF_resul_tel.setText("");
        jTF_resul_mail.setText("");
        jTF_resul_dir.setText("");
        label_resul_estado.setText("");
    }



    private void jTF_resul_cargoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTF_resul_cargoActionPerformed
        // TODO add your handling code here:
        if (jTF_resul_cargo.getSelectedIndex() != -1) {
            String cargo = String.valueOf(jTF_resul_cargo.getSelectedItem());

        }


    }// GEN-LAST:event_jTF_resul_cargoActionPerformed

    private void jTF_resul_tipoidActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTF_resul_tipoidActionPerformed
        // TODO add your handling code here:
        if (jTF_resul_tipoid.getSelectedIndex() != -1) {
            String tipoid = String.valueOf(jTF_resul_tipoid.getSelectedItem());
        }
    }// GEN-LAST:event_jTF_resul_tipoidActionPerformed

    private void campoConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoConsultaUsuarioActionPerformed
        if (campoConsultaUsuario.getSelectedIndex() != -1) {
            String info[] = String.valueOf(campoConsultaUsuario.getSelectedItem()).split(" - ");
            String id = info[2];
            String tipoid = info[1];
            idActual = info[2];
            tipoidActual = info[1];

            estadoventanasEstadoUsuario(false); // Se ocultan los posibles jlabels sobrepuestos

            String[] datos;
            try {
                datos = admUser.mostrarUsuario(id, tipoid);
                if (datos[0] != null) {
                    /*
                     * for (int j = 0; j < datos.length; j++) { System.out.println(datos[j]); }
                     */

                    estadoventanasConsultaUsuario(true);

                    // Aparecen los resultados
                    jTF_resul_tipoid.setSelectedItem(datos[1]);
                    jTF_resul_id.setText(datos[0]);
                    jTF_resul_cargo.setSelectedItem(datos[2]);
                    jTF_resul_nombre.setText(datos[3]);
                    jTF_resul_dir.setText(datos[4]);
                    jTF_resul_tel.setText(datos[5]);
                    jTF_resul_mail.setText(datos[6]);

                    if ("ACTIVO".equals(datos[7])) {
                        label_resul_estado.setText(datos[7]);
                        label_resul_estado.setForeground(new java.awt.Color(0, 153, 51));
                    } else {
                        label_resul_estado.setText(datos[7]);
                        label_resul_estado.setForeground(new java.awt.Color(255, 51, 51));
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ingresado no existe",
                            "Advertencia", JOptionPane.ERROR_MESSAGE);
                    estadoventanasConsultaUsuario(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }// GEN-LAST:event_campoConsultaUsuarioActionPerformed


    private void estadoventanasConsultaUsuario(boolean bol) {
        // Aparecer los labels de consulta
        label_id.setVisible(bol);
        label_cargo.setVisible(bol);
        label_nombre.setVisible(bol);
        label_dir.setVisible(bol);
        label_tel.setVisible(bol);
        label_mail.setVisible(bol);
        label_estado.setVisible(bol);

        // Aparecer los cuadros de consulta
        jTF_resul_id.setVisible(bol);
        jTF_resul_cargo.setVisible(bol);
        jTF_resul_nombre.setVisible(bol);
        jTF_resul_dir.setVisible(bol);
        jTF_resul_tel.setVisible(bol);
        jTF_resul_mail.setVisible(bol);
        jTF_resul_tipoid.setVisible(bol);
        label_resul_estado.setVisible(bol);

    }

    private void estadoventanasEstadoUsuario(boolean bol) {
        // Aparecer los labels de consulta
        label_notificacion.setVisible(bol);
        label_imEstado.setVisible(bol);

        // Aparecer los cuadros de consulta
        label_resulEstado2.setVisible(bol);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
         * feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador("1006054580", "C.C", "Kevin David Rodriguez B").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton actualiarInfo;
    private javax.swing.JPanel barraTitulo;
    private javax.swing.JButton cambiarEstado;
    private javax.swing.JComboBox<String> campoConsultaUsuario;
    private javax.swing.JLabel horaSesion;
    private javax.swing.JComboBox<String> jTF_resul_cargo;
    private javax.swing.JTextField jTF_resul_dir;
    private javax.swing.JTextField jTF_resul_id;
    private javax.swing.JTextField jTF_resul_mail;
    private javax.swing.JTextField jTF_resul_nombre;
    private javax.swing.JTextField jTF_resul_tel;
    private javax.swing.JComboBox<String> jTF_resul_tipoid;
    private javax.swing.JLabel label_cargo;
    private javax.swing.JLabel label_dir;
    private javax.swing.JLabel label_estado;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_imEstado;
    private javax.swing.JLabel label_mail;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_notificacion;
    private javax.swing.JLabel label_resulEstado2;
    private javax.swing.JLabel label_resul_estado;
    private javax.swing.JLabel label_tel;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panelDer;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JPanel reporteFacturas;
    private javax.swing.JPanel reporteGanancias;
    private javax.swing.JPanel reporteNose;
    private javax.swing.JPanel reporteOperadores;
    private javax.swing.JButton reportes;
    private javax.swing.JButton salida;
    private javax.swing.JPanel tabGestiosUsuarios;
    private javax.swing.JTabbedPane tabsReportes;
    private javax.swing.JTabbedPane tabsUsuarios;
    private javax.swing.JLabel tituloSuperior;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables
}
