/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.teleamiguis;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
import static services.reportes.createPrint;
import static services.reportes.createReportView;
import static services.reportes.getConnection;
import modules.administradorUsuarios;

/**
 *
 * @author gyron
 */
public class Administrador extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    /**
     * Creates new form Gerente
     */
    public Administrador() {
        initComponents();
        
        // Hacemos invisibles todos los jlabel de abajo del tab de gestionUsuario
        estadoventanasEstadoUsuario(false); 
        estadoventanasConsultaUsuario(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelGeneral = new javax.swing.JPanel();
        panelIzq = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        rol = new javax.swing.JLabel();
        usuarios = new javax.swing.JButton();
        estadoClientes = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        salida = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        registroNum = new javax.swing.JButton();
        panelDer = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();
        tabsUsuarios = new javax.swing.JTabbedPane();
        tabGestiosUsuarios = new javax.swing.JPanel();
        campoConsultaUsuario = new javax.swing.JTextField();
        botonConsultaUsuario = new javax.swing.JButton();
        label_id = new javax.swing.JLabel();
        label_nom = new javax.swing.JLabel();
        label_apellido = new javax.swing.JLabel();
        label_dir = new javax.swing.JLabel();
        label_tel = new javax.swing.JLabel();
        label_mail = new javax.swing.JLabel();
        label_estado = new javax.swing.JLabel();
        label_resul_estado = new javax.swing.JLabel();
        jTF_resul_nom = new javax.swing.JTextField();
        jTF_resul_id = new javax.swing.JTextField();
        jTF_resul_apellido = new javax.swing.JTextField();
        jTF_resul_dir = new javax.swing.JTextField();
        jTF_resul_tel = new javax.swing.JTextField();
        jTF_resul_mail = new javax.swing.JTextField();
        cambiarEstado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PanelEstado = new javax.swing.JPanel();
        label_resulEstado2 = new javax.swing.JLabel();
        label_notificacion = new javax.swing.JLabel();
        label_imEstado = new javax.swing.JLabel();
        tabConsultaUsuario = new javax.swing.JPanel();
        tabsReportes = new javax.swing.JTabbedPane();
        reporteGanancias = new javax.swing.JPanel();
        reporteFacturas = new javax.swing.JPanel();
        reporteOperadores = new javax.swing.JPanel();
        reporteNose = new javax.swing.JPanel();
        barraTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelGeneral.setBackground(new java.awt.Color(98, 197, 255));
        panelGeneral.setPreferredSize(new java.awt.Dimension(850, 450));
        panelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIzq.setBackground(new java.awt.Color(22, 49, 92));
        panelIzq.setPreferredSize(new java.awt.Dimension(300, 450));
        panelIzq.setLayout(new java.awt.GridBagLayout());

        nombre.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("NOMBRE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelIzq.add(nombre, gridBagConstraints);

        rol.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        rol.setForeground(new java.awt.Color(255, 255, 255));
        rol.setText("ADMINISTRADOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 5);
        panelIzq.add(rol, gridBagConstraints);

        usuarios.setBackground(new java.awt.Color(255, 255, 255));
        usuarios.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        usuarios.setForeground(new java.awt.Color(0, 0, 0));
        usuarios.setText("Usuarios");
        usuarios.setFocusPainted(false);
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 6, 10);
        panelIzq.add(usuarios, gridBagConstraints);

        estadoClientes.setBackground(new java.awt.Color(255, 255, 255));
        estadoClientes.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        estadoClientes.setForeground(new java.awt.Color(0, 0, 0));
        estadoClientes.setText("Clientes");
        estadoClientes.setFocusable(false);
        estadoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoClientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelIzq.add(estadoClientes, gridBagConstraints);

        reportes.setBackground(new java.awt.Color(255, 255, 255));
        reportes.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        reportes.setForeground(new java.awt.Color(0, 0, 0));
        reportes.setText("Reportes");
        reportes.setFocusable(false);
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelIzq.add(reportes, gridBagConstraints);

        salida.setBackground(new java.awt.Color(102, 102, 102));
        salida.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        salida.setForeground(new java.awt.Color(255, 255, 255));
        salida.setText("Salida");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(25, 10, 10, 10);
        panelIzq.add(salida, gridBagConstraints);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/Logo.png"))); // NOI18N
        panelIzq.add(Logo, new java.awt.GridBagConstraints());

        registroNum.setBackground(new java.awt.Color(255, 255, 255));
        registroNum.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        registroNum.setForeground(new java.awt.Color(0, 0, 0));
        registroNum.setText("Registro Num");
        registroNum.setFocusable(false);
        registroNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroNumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelIzq.add(registroNum, gridBagConstraints);

        panelGeneral.add(panelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 450));

        panelDer.setBackground(new java.awt.Color(255, 255, 255,150));
        panelDer.setPreferredSize(new java.awt.Dimension(500, 450));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/fondo2.jpg"))); // NOI18N
        Fondo.setToolTipText("");
        Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabsUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabsUsuarios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsUsuariosStateChanged(evt);
            }
        });

        tabGestiosUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoConsultaUsuario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        campoConsultaUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConsultaUsuarioActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(campoConsultaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 240, 37));

        botonConsultaUsuario.setText("Consultar");
        botonConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaUsuarioActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(botonConsultaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        label_id.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id.setText("Identificación");
        tabGestiosUsuarios.add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 188, -1, -1));
        label_id.setVisible(false);

        label_nom.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_nom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nom.setText("Nombre");
        tabGestiosUsuarios.add(label_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 188, 64, -1));
        label_nom.setVisible(false);

        label_apellido.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_apellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_apellido.setText("Apellidos");
        tabGestiosUsuarios.add(label_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 188, -1, -1));
        label_apellido.setVisible(false);

        label_dir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_dir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dir.setText("Dirección");
        tabGestiosUsuarios.add(label_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 273, 95, -1));
        label_dir.setVisible(false);

        label_tel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_tel.setText("Teléfono");
        tabGestiosUsuarios.add(label_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 273, -1, -1));
        label_tel.setVisible(false);

        label_mail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_mail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_mail.setText("Correo ");
        tabGestiosUsuarios.add(label_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 273, 65, -1));
        label_mail.setVisible(false);

        label_estado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_estado.setText("Estado");
        tabGestiosUsuarios.add(label_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 349, 62, -1));
        label_estado.setVisible(false);

        label_resul_estado.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_resul_estado.setForeground(new java.awt.Color(0, 153, 51));
        label_resul_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabGestiosUsuarios.add(label_resul_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 374, 173, 36));
        label_resul_estado.setVisible(false);

        jTF_resul_nom.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_nom.setEditable(false);
        jTF_resul_nom.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_nom.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_resul_nom.setOpaque(true);
        jTF_resul_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_resul_nomActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(jTF_resul_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 213, 173, 33));
        jTF_resul_nom.setVisible(false);

        jTF_resul_id.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_id.setEditable(false);
        jTF_resul_id.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_id.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_resul_id.setOpaque(true);
        jTF_resul_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_resul_idActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(jTF_resul_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 213, 173, 33));
        jTF_resul_id.setVisible(false);

        jTF_resul_apellido.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_apellido.setEditable(false);
        jTF_resul_apellido.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_apellido.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_resul_apellido.setOpaque(true);
        tabGestiosUsuarios.add(jTF_resul_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 213, 173, 33));
        jTF_resul_apellido.setVisible(false);

        jTF_resul_dir.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_dir.setEditable(false);
        jTF_resul_dir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_dir.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_dir.setOpaque(true);
        tabGestiosUsuarios.add(jTF_resul_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 298, 173, 33));
        jTF_resul_dir.setVisible(false);

        jTF_resul_tel.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_tel.setEditable(false);
        jTF_resul_tel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_tel.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_resul_tel.setOpaque(true);
        tabGestiosUsuarios.add(jTF_resul_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 298, 173, 33));
        jTF_resul_tel.setVisible(false);

        jTF_resul_mail.setBackground(new java.awt.Color(255, 255, 255));
        jTF_resul_mail.setEditable(false);
        jTF_resul_mail.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTF_resul_mail.setForeground(new java.awt.Color(0, 0, 0));
        jTF_resul_mail.setOpaque(true);
        tabGestiosUsuarios.add(jTF_resul_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 298, 173, 33));
        jTF_resul_mail.setVisible(false);

        cambiarEstado.setText("A/D");
        cambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarEstadoActionPerformed(evt);
            }
        });
        tabGestiosUsuarios.add(cambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Digite el documento de identidad:");
        tabGestiosUsuarios.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 300, -1));

        label_resulEstado2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_resulEstado2.setForeground(new java.awt.Color(0, 153, 51));
        label_resulEstado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        label_notificacion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_notificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        this.setVisible(false);
        label_imEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/estado_usuario.png"))); // NOI18N
        label_imEstado.setOpaque(true);

        javax.swing.GroupLayout PanelEstadoLayout = new javax.swing.GroupLayout(PanelEstado);
        PanelEstado.setLayout(PanelEstadoLayout);
        PanelEstadoLayout.setHorizontalGroup(
            PanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadoLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(label_imEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstadoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(label_notificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEstadoLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(label_resulEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        PanelEstadoLayout.setVerticalGroup(
            PanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(PanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_imEstado)
                    .addGroup(PanelEstadoLayout.createSequentialGroup()
                        .addComponent(label_notificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_resulEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        label_resul_estado.setVisible(false);

        tabGestiosUsuarios.add(PanelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 720, 250));

        tabsUsuarios.addTab("Gestion", tabGestiosUsuarios);

        tabConsultaUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tabsUsuarios.addTab("Consulta general", tabConsultaUsuario);

        tabsReportes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsReportesStateChanged(evt);
            }
        });

        reporteGanancias.setLayout(new java.awt.BorderLayout());
        tabsReportes.addTab("Ganancias", reporteGanancias);

        reporteFacturas.setLayout(new java.awt.BorderLayout());
        tabsReportes.addTab("Facturas", reporteFacturas);

        reporteOperadores.setLayout(new java.awt.BorderLayout());
        tabsReportes.addTab("Operadores", reporteOperadores);

        reporteNose.setLayout(new java.awt.BorderLayout());
        tabsReportes.addTab("Nose", reporteNose);

        javax.swing.GroupLayout panelDerLayout = new javax.swing.GroupLayout(panelDer);
        panelDer.setLayout(panelDerLayout);
        panelDerLayout.setHorizontalGroup(
            panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabsUsuarios))
            .addGroup(panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelDerLayout.setVerticalGroup(
            panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addGroup(panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDerLayout.createSequentialGroup()
                    .addComponent(tabsUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDerLayout.createSequentialGroup()
                    .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        //Poner invisible al inicio tab Usuarios
        tabsUsuarios.setVisible(false);
        //Poner invisible all inicio
        tabsReportes.setVisible(false);

        panelGeneral.add(panelDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 700, 450));
        panelDer.getAccessibleContext().setAccessibleDescription("");

        barraTitulo.setBackground(new java.awt.Color(43, 41, 40));
        barraTitulo.setForeground(new java.awt.Color(255, 255, 255));
        barraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraTituloMouseDragged(evt);
            }
        });
        barraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraTituloMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrador");

        javax.swing.GroupLayout barraTituloLayout = new javax.swing.GroupLayout(barraTitulo);
        barraTitulo.setLayout(barraTituloLayout);
        barraTituloLayout.setHorizontalGroup(
            barraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraTituloLayout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel1)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        barraTituloLayout.setVerticalGroup(
            barraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGeneral.add(barraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        tabsReportes.setVisible(false);
        tabsUsuarios.setVisible(true);
        panelGeneral.repaint();
        panelGeneral.revalidate();
        panelDer.repaint();
        panelDer.revalidate();
        reportes.setEnabled(true);
        usuarios.setEnabled(false);
        registroNum.setEnabled(true);
        estadoClientes.setEnabled(true);

    }//GEN-LAST:event_usuariosActionPerformed

    private void barraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraTituloMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraTituloMouseDragged

    private void barraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraTituloMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraTituloMousePressed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_salidaActionPerformed

    private void registroNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroNumActionPerformed
        tabsReportes.setVisible(false);
        tabsUsuarios.setVisible(false);
        panelGeneral.repaint();
        panelGeneral.revalidate();
        panelDer.repaint();
        panelDer.revalidate();
        reportes.setEnabled(true);
        usuarios.setEnabled(true);
        registroNum.setEnabled(false);
        estadoClientes.setEnabled(true);

    }//GEN-LAST:event_registroNumActionPerformed

    private void estadoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoClientesActionPerformed
        tabsReportes.setVisible(false);
        tabsUsuarios.setVisible(false);
        panelGeneral.repaint();
        panelGeneral.revalidate();
        panelDer.repaint();
        panelDer.revalidate();
        reportes.setEnabled(true);
        usuarios.setEnabled(true);
        registroNum.setEnabled(true);
        estadoClientes.setEnabled(false);

    }//GEN-LAST:event_estadoClientesActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        tabsReportes.setVisible(true);
        tabsUsuarios.setVisible(false);
        panelGeneral.repaint();
        panelGeneral.revalidate();
        panelDer.repaint();
        panelDer.revalidate();
        reportes.setEnabled(false);
        usuarios.setEnabled(true);
        registroNum.setEnabled(true);
        estadoClientes.setEnabled(true);

    }//GEN-LAST:event_reportesActionPerformed

    private void tabsReportesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsReportesStateChanged
        if (tabsReportes.getSelectedIndex() == 0) {
            try {
                Connection conn = getConnection();
                Map<String, Object> parameters = new HashMap<>();
                parameters.put("title", "Soy un titulo mamon");
                String jrxml = "/reports/reportes.jrxml";
                JasperPrint print = createPrint(parameters, jrxml, conn);
                JRViewer view = createReportView(print);
                reporteGanancias.add(view);
                conn.close();

            } catch (JRException | IOException | SQLException ex) {
                Logger.getLogger(Gerente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
//        else{
//        
//        }

    }//GEN-LAST:event_tabsReportesStateChanged

    private void botonConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaUsuarioActionPerformed
        // TODO add your handling code here:
        String id;
        id = campoConsultaUsuario.getText();

        estadoventanasEstadoUsuario(false);  // Se ocultan los posibles jlabels sobrepuestos
        try {
            administradorUsuarios admUser = new administradorUsuarios();
            String[] datos = admUser.mostrarUsuario(id);

            if (datos[0] != null) {
                for (int j = 0; j < datos.length; j++) {
                    System.out.println(datos[j]);
                }

                estadoventanasConsultaUsuario(true);

                //Aparecen los resultados
                jTF_resul_id.setText(datos[1] + " " + datos[0]);
                jTF_resul_nom.setText(datos[2]);
                jTF_resul_apellido.setText(datos[3]);
                jTF_resul_dir.setText(datos[4]);
                jTF_resul_tel.setText(datos[5]);
                jTF_resul_mail.setText(datos[6]);

                if ("ACTIVO".equals(datos[7])){
                    label_resul_estado.setText(datos[7]);
                    label_resul_estado.setForeground(new java.awt.Color(0,153,51));
                }else {
                    label_resul_estado.setText(datos[7]);
                    label_resul_estado.setForeground(new java.awt.Color(255,51,51));
                }

            } else {
                JOptionPane.showMessageDialog(null,"El usuario ingresado no existe","Advertencia" ,JOptionPane.ERROR_MESSAGE);
                estadoventanasConsultaUsuario(false);
            }
        } catch (IOException | SQLException e) {
            System.out.println("No fue posible crear la clase administradorUsuarios");
        }
    }//GEN-LAST:event_botonConsultaUsuarioActionPerformed

    private void campoConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConsultaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConsultaUsuarioActionPerformed

    private void tabsUsuariosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsUsuariosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tabsUsuariosStateChanged

    private void cambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarEstadoActionPerformed
        // TODO add your handling code here:
        estadoventanasConsultaUsuario(false); // Se ocultan los posibles jlabels sobrepuestos
        
        int op; 
        String id = campoConsultaUsuario.getText(); 
        String user; 
        try {
            administradorUsuarios admUser = new administradorUsuarios(); // se crea una instancia de la clase administradorUsuarios
            String[] datos = admUser.mostrarUsuario(id); 
            
            if ("ACTIVO".equals(datos[7])) { // En el caso de que esté activo
                user = "" + datos[2] + " " + datos[3] + " esta a punto de ser desactivado, ¿desea continuar?"; 
                
                op = JOptionPane.showConfirmDialog(null, user, "Desactivar usuario", JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/usedPictures/inactivar.png")));
                
               if (op == 0) {
                   admUser.cambiaEstadoUsuario(id, "false"); 
                   label_notificacion.setText("El usuario con id " + id + " ha sido:"); 
                   label_resulEstado2.setText("DESACTIVADO");
                   label_resulEstado2.setForeground(new java.awt.Color(255,51,51)); // color rojo
                   estadoventanasEstadoUsuario(true); 
               } else {
                   JOptionPane.showMessageDialog(null, "No se han aplicado cambios", "Notificacion", JOptionPane.INFORMATION_MESSAGE,
                           new javax.swing.ImageIcon(getClass().getResource("/usedPictures/estado_usuario.png")));
                   estadoventanasEstadoUsuario(false); 
                  }
            } else { // En el caso de que esté inactivo
                user = "" + datos[2] + " " + datos[3] + " esta a punto de ser reactivado, ¿desea continuar?"; 
                op = JOptionPane.showConfirmDialog(null, user, "Activar usuario", JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/usedPictures/activar.png")));
                if (op == 0)  {
                   admUser.cambiaEstadoUsuario(id, "true"); 
                   label_notificacion.setText("El usuario con id " + id + " ha sido:"); 
                   label_resulEstado2.setText("ACTIVADO"); 
                   label_resulEstado2.setForeground(new java.awt.Color(0,153,51)); // color verde
                   estadoventanasEstadoUsuario(true); 
                } else { 
                   JOptionPane.showMessageDialog(null, "No se han aplicado cambios", "Notificacion", JOptionPane.INFORMATION_MESSAGE,
                           new javax.swing.ImageIcon(getClass().getResource("/usedPictures/estado_usuario.png")));
                   estadoventanasEstadoUsuario(false); 
                }
            }
            
        } catch (IOException | SQLException e) {
            System.out.println("No fue posible crear la clase administradorUsuarios");
            }
    }//GEN-LAST:event_cambiarEstadoActionPerformed

    private void jTF_resul_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_resul_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_resul_idActionPerformed

    private void jTF_resul_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_resul_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_resul_nomActionPerformed


        private void estadoventanasConsultaUsuario(boolean bol){
          //Aparecer los labels de consulta
                        label_id.setVisible(bol);
                        label_nom.setVisible(bol);
                        label_apellido.setVisible(bol);
                        label_dir.setVisible(bol);
                        label_tel.setVisible(bol);
                        label_mail.setVisible(bol);
                        label_estado.setVisible(bol);

                        //Aparecer los cuadros de consulta
                        jTF_resul_id.setVisible(bol);
                        jTF_resul_nom.setVisible(bol);
                        jTF_resul_apellido.setVisible(bol);
                        jTF_resul_dir.setVisible(bol);
                        jTF_resul_tel.setVisible(bol);
                        jTF_resul_mail.setVisible(bol);
                        label_resul_estado.setVisible(bol);

        }
        
        private void estadoventanasEstadoUsuario(boolean bol){
            // Aparecer los labels de consulta
            label_notificacion.setVisible(bol);
            label_imEstado.setVisible(bol); 
            
            // Aparecer los cuadros de consulta
            label_resulEstado2.setVisible(bol);
        }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelEstado;
    private javax.swing.JPanel barraTitulo;
    private javax.swing.JButton botonConsultaUsuario;
    private javax.swing.JButton cambiarEstado;
    private javax.swing.JTextField campoConsultaUsuario;
    private javax.swing.JButton estadoClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTF_resul_apellido;
    private javax.swing.JTextField jTF_resul_dir;
    private javax.swing.JTextField jTF_resul_id;
    private javax.swing.JTextField jTF_resul_mail;
    private javax.swing.JTextField jTF_resul_nom;
    private javax.swing.JTextField jTF_resul_tel;
    private javax.swing.JLabel label_apellido;
    private javax.swing.JLabel label_dir;
    private javax.swing.JLabel label_estado;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_imEstado;
    private javax.swing.JLabel label_mail;
    private javax.swing.JLabel label_nom;
    private javax.swing.JLabel label_notificacion;
    private javax.swing.JLabel label_resulEstado2;
    private javax.swing.JLabel label_resul_estado;
    private javax.swing.JLabel label_tel;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panelDer;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JButton registroNum;
    private javax.swing.JPanel reporteFacturas;
    private javax.swing.JPanel reporteGanancias;
    private javax.swing.JPanel reporteNose;
    private javax.swing.JPanel reporteOperadores;
    private javax.swing.JButton reportes;
    private javax.swing.JLabel rol;
    private javax.swing.JButton salida;
    private javax.swing.JPanel tabConsultaUsuario;
    private javax.swing.JPanel tabGestiosUsuarios;
    private javax.swing.JTabbedPane tabsReportes;
    private javax.swing.JTabbedPane tabsUsuarios;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables
}
